# Generated by Django 5.0.1 on 2024-02-04 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beperking',
            fields=[
                ('beperking_id', models.AutoField(primary_key=True, serialize=False)),
                ('beperking', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'beperkingen',
            },
        ),
        migrations.CreateModel(
            name='Medewerker',
            fields=[
                ('medewerker_id', models.AutoField(primary_key=True, serialize=False)),
                ('voornaam', models.CharField(max_length=255)),
                ('achternaam', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=6)),
                ('huisnummer', models.IntegerField()),
                ('geslacht', models.CharField(max_length=10)),
                ('emailadres', models.CharField(max_length=255)),
                ('telefoonnummer', models.CharField(max_length=15)),
                ('geboortedatum', models.DateField()),
                ('admin', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gebruikersnaam', models.CharField(default='', max_length=255)),
                ('wachtwoord', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'medewerkers',
            },
        ),
        migrations.CreateModel(
            name='Onderzoek',
            fields=[
                ('onderzoek_id', models.AutoField(primary_key=True, serialize=False)),
                ('titel', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('beschikbaar', models.CharField(max_length=50)),
                ('beschrijving', models.CharField(max_length=255)),
                ('datum_vanaf', models.DateField()),
                ('datum_tot', models.DateField()),
                ('type_onderzoek', models.CharField(max_length=50)),
                ('locatie', models.CharField(max_length=255)),
                ('met_beloning', models.BooleanField()),
                ('beloning', models.TextField(blank=True, null=True)),
                ('doelgroep_leeftijd_van', models.IntegerField()),
                ('doelgroep_leeftijd_tot', models.IntegerField()),
                ('doelgroep_beperking', models.CharField(max_length=100)),
                ('onderzoek_vragen_id', models.IntegerField()),
            ],
            options={
                'db_table': 'onderzoeken',
            },
        ),
        migrations.CreateModel(
            name='Organisatie',
            fields=[
                ('organisatie_id', models.AutoField(primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('beschrijving', models.TextField()),
                ('contactpersoon', models.CharField(max_length=255)),
                ('emailadres', models.EmailField(max_length=255)),
                ('telefoonnummer', models.CharField(max_length=15)),
                ('overige_details', models.TextField()),
            ],
            options={
                'db_table': 'organisaties',
            },
        ),
        migrations.CreateModel(
            name='Ervaringsdeskundige',
            fields=[
                ('deskundige_id', models.AutoField(primary_key=True, serialize=False)),
                ('voornaam', models.CharField(blank=True, max_length=255, null=True)),
                ('achternaam', models.CharField(blank=True, max_length=255, null=True)),
                ('geboortedatum', models.DateField(blank=True, null=True)),
                ('telefoonnummer', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('geslacht', models.CharField(blank=True, max_length=10, null=True)),
                ('postcode', models.CharField(blank=True, max_length=6, null=True)),
                ('huisnummer', models.IntegerField(blank=True, null=True)),
                ('soort_beperking', models.TextField(blank=True, null=True)),
                ('hulpmiddelen', models.TextField(blank=True, null=True)),
                ('bijzonderheden', models.TextField(blank=True, null=True)),
                ('account_status', models.IntegerField(default=0)),
                ('beperking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrators.beperking')),
                ('onderzoek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrators.onderzoek')),
            ],
            options={
                'db_table': 'ervaringsdeskundigen',
            },
        ),
        migrations.AddField(
            model_name='onderzoek',
            name='organisatie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrators.organisatie'),
        ),
    ]
