# Generated by Django 5.0.1 on 2024-02-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0002_ervaringsdeskundige_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ervaringsdeskundige',
            name='beperking',
        ),
        migrations.RemoveField(
            model_name='ervaringsdeskundige',
            name='onderzoek',
        ),
        migrations.DeleteModel(
            name='Medewerker',
        ),
        migrations.RemoveField(
            model_name='onderzoek',
            name='organisatie',
        ),
        migrations.DeleteModel(
            name='Beperking',
        ),
        migrations.DeleteModel(
            name='Ervaringsdeskundige',
        ),
        migrations.DeleteModel(
            name='Onderzoek',
        ),
        migrations.DeleteModel(
            name='Organisatie',
        ),
    ]
