# Generated by Django 5.0.1 on 2024-02-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0002_ervaringsdeskundige_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='medewerker',
            name='test',
            field=models.IntegerField(default='0'),
        ),
    ]
