# Generated by Django 5.0.1 on 2024-02-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0003_medewerker_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medewerker',
            name='test',
            field=models.IntegerField(default='0'),
        ),
    ]
