# Generated by Django 5.0.2 on 2024-03-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0004_alter_medewerker_test'),
        ('administrators', '0004_initial'),
    ]

    operations = [
    ]
