# Generated by Django 5.0.2 on 2024-03-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0007_remove_ervaringsdeskundige_bericht_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ervaringsdeskundige',
            name='bericht_status',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
    ]
