# Generated by Django 5.0.2 on 2024-03-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0008_merge_20240312_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='ervaringsdeskundige',
            name='bericht_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
