# Generated by Django 5.0.1 on 2024-02-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_organisatie_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisatie',
            options={},
        ),
        migrations.AlterField(
            model_name='organisatie',
            name='achternaam',
            field=models.CharField(db_column='last_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='organisatie',
            name='email',
            field=models.CharField(db_column='email', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='organisatie',
            name='voornaam',
            field=models.CharField(db_column='first_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='organisatie',
            name='wachtwoord',
            field=models.CharField(db_column='password', max_length=255),
        ),
        migrations.AlterModelTable(
            name='organisatie',
            table='organisatie',
        ),
    ]
