# Generated by Django 5.0.1 on 2024-02-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_organisatie_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisatie',
            name='achternaam',
        ),
        migrations.RemoveField(
            model_name='organisatie',
            name='voornaam',
        ),
        migrations.RemoveField(
            model_name='organisatie',
            name='wachtwoord',
        ),
        migrations.AddField(
            model_name='organisatie',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='organisatie',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='organisatie',
            name='password',
            field=models.CharField(default=0, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
