# Generated by Django 5.0.1 on 2024-02-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_organisatie_achternaam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisatie',
            name='token',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
