# Generated by Django 5.0.1 on 2024-02-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_organisatie_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisatie',
            name='token',
        ),
    ]
