# Generated by Django 5.0.1 on 2024-02-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_organisatie_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisatie',
            name='status',
            field=models.CharField(default='nieuw', max_length=255),
        ),
        migrations.AddField(
            model_name='organisatie',
            name='token',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
