# Generated by Django 5.0.1 on 2024-02-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_organisatie_status_organisatie_token'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organisatie',
            table='organisaties',
        ),
    ]
