# Generated by Django 5.0.1 on 2024-02-24 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_organisatie_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisatie',
            name='status',
            field=models.CharField(default='Nieuw', max_length=255),
        ),
        migrations.CreateModel(
            name='Onderzoek',
            fields=[
                ('onderzoek_id', models.AutoField(primary_key=True, serialize=False)),
                ('titel', models.CharField(max_length=255)),
                ('status', models.CharField(default='Nieuw', max_length=255)),
                ('beschikbaar', models.BooleanField(default=True)),
                ('beschrijving', models.TextField()),
                ('startdatum', models.DateField()),
                ('einddatum', models.DateField()),
                ('type_onderzoek', models.CharField(max_length=255)),
                ('locatie', models.CharField(max_length=255)),
                ('met_beloning', models.BooleanField(default=False)),
                ('beloning', models.CharField(max_length=255)),
                ('doelgroep_leeftijd_van', models.IntegerField(max_length=255)),
                ('doelgroep_leeftijd_tot', models.IntegerField(max_length=255)),
                ('doelgroep_beperking', models.CharField(max_length=255)),
                ('organisatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onderzoeken', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onderzoeken',
            },
        ),
    ]
