# Generated by Django 5.0.1 on 2024-02-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_organisatie_status_onderzoek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onderzoek',
            name='beloning',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
