# Generated by Django 5.0.1 on 2024-02-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_onderzoek_beloning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onderzoek',
            name='doelgroep_leeftijd_tot',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='onderzoek',
            name='doelgroep_leeftijd_van',
            field=models.IntegerField(),
        ),
    ]
