# Generated by Django 5.0.1 on 2024-02-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_onderzoek_doelgroep_leeftijd_tot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onderzoek',
            name='titel',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
