# Generated by Django 5.0.1 on 2024-02-27 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_alter_onderzoek_titel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vragen',
            fields=[
                ('vraag_id', models.AutoField(primary_key=True, serialize=False)),
                ('vraag', models.CharField(max_length=255)),
                ('beschrijving', models.TextField()),
                ('categorie', models.CharField(max_length=255)),
                ('onderzoek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vragen', to='companies.onderzoek')),
            ],
            options={
                'db_table': 'vragen',
            },
        ),
    ]
